wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 1
gamma:
  value: 0.7055512323008033
milestones:
  value:
  - 3
  - 7
  - 15
optimizer:
  value: sgd
second_layer_size:
  value: 128
starting_lr:
  value: 0.525605843391354
