wandb_version: 1

batch_size:
  value: 25
gamma:
  value: 0.6425152136750777
milestones:
  value:
  - 1
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.2738997176263791
sweep_epochs:
  value: 3
