wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 2
gamma:
  value: 0.19250974339531943
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.0941837947195406
