wandb_version: 1

batch_size:
  value: 20
gamma:
  value: 0.32516059317319607
milestones:
  value:
  - 2
  - 6
optimizer:
  value: sgd
second_layer_size:
  value: 512
starting_lr:
  value: 0.02936482438795629
sweep_epochs:
  value: 4
