wandb_version: 1

batch_size:
  value: 5
gamma:
  value: 0.18522144890039585
milestones:
  value:
  - 2
  - 6
optimizer:
  value: adam
second_layer_size:
  value: 128
starting_lr:
  value: 0.2121066907486712
sweep_epochs:
  value: 4
