wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 40
gamma:
  value: 0.08105407216740733
milestones:
  value:
  - 5
  - 10
  - 15
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.4502415626393191
