wandb_version: 1

batch_size:
  value: 15
epochs:
  value: 40
gamma:
  value: 0.35298799579187884
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 128
starting_lr:
  value: 0.13724234434980756
