wandb_version: 1

batch_size:
  value: 15
epochs:
  value: 10
gamma:
  value: 0.5707734850281746
milestones:
  value:
  - 5
  - 10
  - 15
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.7985034111771873
