wandb_version: 1

batch_size:
  value: 15
epochs:
  value: 40
gamma:
  value: 0.2977265416865636
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.21712715541480268
