wandb_version: 1

batch_size:
  value: 15
epochs:
  value: 40
gamma:
  value: 0.44485043880526026
milestones:
  value:
  - 5
  - 10
  - 15
optimizer:
  value: adam
second_layer_size:
  value: 128
starting_lr:
  value: 0.698146165153625
