wandb_version: 1

batch_size:
  value: 20
epochs:
  value: 40
gamma:
  value: 0.2296716770347979
milestones:
  value:
  - 5
  - 10
  - 15
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.8428768530617986
