wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 40
gamma:
  value: 0.4154516216073174
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.42015783335382506
