wandb_version: 1

batch_size:
  value: 25
epochs:
  value: 10
gamma:
  value: 0.4556831758421757
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.6779352324116505
