wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 10
gamma:
  value: 0.17973753824236532
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.5187087797547744
