wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 10
gamma:
  value: 0.24428783857590175
milestones:
  value:
  - 5
  - 10
  - 15
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.6614252222722136
