wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 40
gamma:
  value: 0.26234434516425087
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 128
starting_lr:
  value: 0.9017530957827012
