wandb_version: 1

batch_size:
  value: 20
epochs:
  value: 40
gamma:
  value: 0.0357811615262187
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.753576505458227
