wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 10
gamma:
  value: 0.5565986718809034
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 128
starting_lr:
  value: 0.263992788284929
