wandb_version: 1

batch_size:
  value: 20
epochs:
  value: 10
gamma:
  value: 0.11685091989141286
milestones:
  value:
  - 5
  - 10
  - 15
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.31941359550820964
