wandb_version: 1

batch_size:
  value: 20
epochs:
  value: 40
gamma:
  value: 0.6236454921753279
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.8816028340033792
