wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 10
gamma:
  value: 0.6060657715774262
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.6946377864246006
