wandb_version: 1

batch_size:
  value: 15
epochs:
  value: 2
gamma:
  value: 0.6599774598771966
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.14571414512785835
