wandb_version: 1

batch_size:
  value: 20
epochs:
  value: 1
gamma:
  value: 0.24565230577807423
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 512
starting_lr:
  value: 0.01253525611811366
