wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 1
gamma:
  value: 0.27049763135363797
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.2874722212630278
