wandb_version: 1

batch_size:
  value: 15
epochs:
  value: 40
gamma:
  value: 0.12296539455850763
milestones:
  value:
  - 5
  - 10
  - 15
optimizer:
  value: sgd
second_layer_size:
  value: 128
starting_lr:
  value: 0.6174494830909982
