wandb_version: 1

batch_size:
  value: 25
epochs:
  value: 30
gamma:
  value: 0.7348050888275203
milestones:
  value:
  - 5
  - 10
  - 15
  - 20
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.8320679850372874
