wandb_version: 1

batch_size:
  value: 20
epochs:
  value: 30
gamma:
  value: 0.09467707289598776
milestones:
  value:
  - 5
  - 7
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.2358945919871744
