wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 2
gamma:
  value: 0.15292331946497892
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.054558653715931306
