wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 1
gamma:
  value: 0.3856437251185421
milestones:
  value:
  - 5
  - 7
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.6088100786874271
