wandb_version: 1

batch_size:
  value: 25
epochs:
  value: 15
gamma:
  value: 0.5223509759951455
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 512
starting_lr:
  value: 0.3952081772026779
