wandb_version: 1

batch_size:
  value: 15
epochs:
  value: 30
gamma:
  value: 0.22949417487967028
milestones:
  value:
  - 5
  - 7
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.19671742737054623
