wandb_version: 1

batch_size:
  value: 10
gamma:
  value: 0.47369651230313314
milestones:
  value:
  - 2
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.012880683452971897
sweep_epochs:
  value: 3
