wandb_version: 1

batch_size:
  value: 15
epochs:
  value: 2
gamma:
  value: 0.5253769037312864
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.24807644640271953
