wandb_version: 1

batch_size:
  value: 15
gamma:
  value: 0.26146120157039937
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 128
starting_lr:
  value: 0.16507250714754984
sweep_epochs:
  value: 3
