wandb_version: 1

batch_size:
  value: 20
gamma:
  value: 0.4824034742370666
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.3495586990001535
sweep_epochs:
  value: 3
