wandb_version: 1

batch_size:
  value: 25
epochs:
  value: 2
gamma:
  value: 0.41057011180617703
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 128
starting_lr:
  value: 0.3092044021742945
