wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 2
gamma:
  value: 0.03908163925759612
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 128
starting_lr:
  value: 0.28185354449108224
