wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 2
gamma:
  value: 0.1102832912712927
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.11324242254844456
