wandb_version: 1

batch_size:
  value: 25
gamma:
  value: 0.38300635608545663
milestones:
  value:
  - 2
  - 3
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.2049186891646557
sweep_epochs:
  value: 4
