wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1660165490
    t:
      1:
      - 55
      2:
      - 55
      4: 3.10.2
      5: 0.12.21
      8:
      - 3
      - 5
