wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1657214227
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      4: 3.10.2
      5: 0.12.20
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 5
epochs:
  desc: null
  value: 1
gamma:
  desc: null
  value: 0.04972920435231164
milestones:
  desc: null
  value:
  - 3
  - 7
  - 15
optimizer:
  desc: null
  value: sgd
second_layer_size:
  desc: null
  value: 256
starting_lr:
  desc: null
  value: 0.33324980940613996
