wandb_version: 1

batch_size:
  value: 10
gamma:
  value: 0.6074253811956116
milestones:
  value:
  - 2
  - 6
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.2826027698190724
sweep_epochs:
  value: 4
