wandb_version: 1

batch_size:
  value: 10
gamma:
  value: 0.11699431540666969
milestones:
  value:
  - 2
  - 6
optimizer:
  value: adam
second_layer_size:
  value: 128
starting_lr:
  value: 0.37883345946207336
sweep_epochs:
  value: 4
