wandb_version: 1

batch_size:
  value: 25
epochs:
  value: 5
gamma:
  value: 0.9771837210491012
milestones:
  value:
  - 5
  - 7
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.4798878675029121
