wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 5
gamma:
  value: 0.9623519605967064
milestones:
  value:
  - 5
  - 10
  - 15
optimizer:
  value: sgd
second_layer_size:
  value: 128
starting_lr:
  value: 0.056256445615185655
