wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 40
gamma:
  value: 0.4454552949650603
milestones:
  value:
  - 5
  - 10
  - 15
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.564377616552946
