wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 30
gamma:
  value: 0.4594985578016384
milestones:
  value:
  - 3
  - 7
  - 15
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.3668807427708367
