wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 40
gamma:
  value: 0.18712528824880825
milestones:
  value:
  - 3
  - 7
  - 15
optimizer:
  value: sgd
second_layer_size:
  value: 128
starting_lr:
  value: 0.5528965781312151
