wandb_version: 1

batch_size:
  value: 20
epochs:
  value: 30
gamma:
  value: 0.5051827460083702
milestones:
  value:
  - 5
  - 10
  - 15
  - 20
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.2089416868491061
