wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 30
gamma:
  value: 0.15184218158725132
milestones:
  value:
  - 3
  - 7
  - 15
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.3620634495768185
