wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 40
gamma:
  value: 0.10245973236797314
milestones:
  value:
  - 3
  - 7
  - 15
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.3961076415110167
