wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 20
gamma:
  value: 0.7125703109429558
milestones:
  value:
  - 5
  - 10
  - 15
  - 20
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.06118435161950101
