wandb_version: 1

batch_size:
  value: 25
epochs:
  value: 40
gamma:
  value: 0.15824875142572517
milestones:
  value:
  - 3
  - 7
  - 15
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.6887399023551523
