wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 20
gamma:
  value: 0.17357780907529669
milestones:
  value:
  - 5
  - 7
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.5140088196006766
