wandb_version: 1

batch_size:
  value: 15
epochs:
  value: 1
gamma:
  value: 0.8490386721577153
milestones:
  value:
  - 5
  - 10
  - 15
optimizer:
  value: sgd
second_layer_size:
  value: 512
starting_lr:
  value: 0.3628941514889171
