wandb_version: 1

batch_size:
  value: 30
epochs:
  value: 1
gamma:
  value: 0.16199490894570157
milestones:
  value:
  - 3
  - 7
  - 15
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.48272300595250983
