wandb_version: 1

batch_size:
  value: 30
gamma:
  value: 0.33111381107287263
milestones:
  value:
  - 2
  - 6
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.09584761430791096
sweep_epochs:
  value: 4
