wandb_version: 1

batch_size:
  value: 5
gamma:
  value: 0.4696269576774483
milestones:
  value:
  - 2
  - 6
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.3742987757578089
sweep_epochs:
  value: 4
