wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 2
gamma:
  value: 0.626269300786633
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 128
starting_lr:
  value: 0.33443301874274933
