wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 2
gamma:
  value: 0.5424400541698724
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.22541160697809373
