wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 2
gamma:
  value: 0.29381855979415805
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.3279897921505988
