wandb_version: 1

batch_size:
  value: 15
epochs:
  value: 15
gamma:
  value: 0.16792632303774108
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 128
starting_lr:
  value: 0.0380682574837926
