wandb_version: 1

batch_size:
  value: 25
epochs:
  value: 15
gamma:
  value: 0.6073507097043032
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 512
starting_lr:
  value: 0.3340755193186936
