wandb_version: 1

batch_size:
  value: 15
epochs:
  value: 15
gamma:
  value: 0.04236021043896271
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.27640413632868915
