wandb_version: 1

batch_size:
  value: 25
epochs:
  value: 15
gamma:
  value: 0.0902733423675263
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.2863511379441504
