wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 15
gamma:
  value: 0.5606958057924633
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.0680180626448179
