wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 1
gamma:
  value: 0.1052895302898689
milestones:
  value:
  - 3
  - 7
  - 15
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.8929622682010088
