wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 1
gamma:
  value: 0.3281830292387216
milestones:
  value:
  - 5
  - 10
  - 15
optimizer:
  value: sgd
second_layer_size:
  value: 512
starting_lr:
  value: 0.7624899746423136
