wandb_version: 1

batch_size:
  value: 15
epochs:
  value: 20
gamma:
  value: 0.9700648999278694
milestones:
  value:
  - 3
  - 7
  - 15
optimizer:
  value: sgd
second_layer_size:
  value: 512
starting_lr:
  value: 0.6808971274726784
