wandb_version: 1

batch_size:
  value: 5
gamma:
  value: 0.023855678584755312
milestones:
  value:
  - 1
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.17763680412340618
sweep_epochs:
  value: 3
