wandb_version: 1

batch_size:
  value: 10
gamma:
  value: 0.2513030693243379
milestones:
  value:
  - 1
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.2751337001950877
sweep_epochs:
  value: 3
