wandb_version: 1

batch_size:
  value: 20
epochs:
  value: 2
gamma:
  value: 0.26080603682151426
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.08603458643348103
