wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 1
gamma:
  value: 0.8458643095733316
milestones:
  value:
  - 5
  - 10
  - 15
optimizer:
  value: sgd
second_layer_size:
  value: 128
starting_lr:
  value: 0.4579782225415901
