wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 1
gamma:
  value: 0.01349320782172743
milestones:
  value:
  - 5
  - 7
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 512
starting_lr:
  value: 0.8238910966776264
