wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 1
gamma:
  value: 0.2760197028728565
milestones:
  value:
  - 3
  - 7
  - 15
optimizer:
  value: adam
second_layer_size:
  value: 128
starting_lr:
  value: 0.8739897246659398
