wandb_version: 1

batch_size:
  value: 20
gamma:
  value: 0.5864371683520347
milestones:
  value:
  - 2
  - 3
optimizer:
  value: sgd
second_layer_size:
  value: 128
starting_lr:
  value: 0.03491303757366208
sweep_epochs:
  value: 4
