wandb_version: 1

batch_size:
  value: 25
epochs:
  value: 2
gamma:
  value: 0.410944675371423
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.22100261301739088
