wandb_version: 1

batch_size:
  value: 25
gamma:
  value: 0.23919926401097777
milestones:
  value:
  - 2
  - 4
optimizer:
  value: adam
second_layer_size:
  value: 128
starting_lr:
  value: 0.3997165444914091
sweep_epochs:
  value: 10
