wandb_version: 1

batch_size:
  value: 25
epochs:
  value: 2
gamma:
  value: 0.25734599448244627
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.02553454968792271
