wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 1
gamma:
  value: 0.5687557099716009
milestones:
  value:
  - 5
  - 7
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 128
starting_lr:
  value: 0.7207702451256123
