wandb_version: 1

batch_size:
  value: 20
epochs:
  value: 1
gamma:
  value: 0.2755324042675514
milestones:
  value:
  - 5
  - 7
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.7683978421516229
