wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 1
gamma:
  value: 0.04219100170835086
milestones:
  value:
  - 5
  - 10
  - 15
optimizer:
  value: sgd
second_layer_size:
  value: 512
starting_lr:
  value: 0.16059179272872057
