wandb_version: 1

batch_size:
  value: 20
epochs:
  value: 2
gamma:
  value: 0.41637055792053657
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.08494418850223456
