wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 1
gamma:
  value: 0.04972920435231164
milestones:
  value:
  - 3
  - 7
  - 15
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.33324980940613996
