wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 1
gamma:
  value: 0.3578083035093814
milestones:
  value:
  - 3
  - 7
  - 15
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.09213576824818502
