wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 1
gamma:
  value: 0.41754818771459135
milestones:
  value:
  - 5
  - 7
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 128
starting_lr:
  value: 0.9650661857325328
