wandb_version: 1

batch_size:
  value: 25
epochs:
  value: 2
gamma:
  value: 0.293667324653003
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 256
starting_lr:
  value: 0.34047986530059904
