wandb_version: 1

batch_size:
  value: 10
gamma:
  value: 0.3512338761732713
milestones:
  value:
  - 2
  - 6
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.3857495014852663
sweep_epochs:
  value: 4
