wandb_version: 1

batch_size:
  value: 5
gamma:
  value: 0.6352611658236139
milestones:
  value:
  - 2
  - 6
optimizer:
  value: adam
second_layer_size:
  value: 256
starting_lr:
  value: 0.0672343368155328
sweep_epochs:
  value: 4
