wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 30
gamma:
  value: 0.35430295024636155
milestones:
  value:
  - 3
  - 7
  - 15
optimizer:
  value: adam
second_layer_size:
  value: 128
starting_lr:
  value: 0.8163040142587388
