wandb_version: 1

batch_size:
  value: 25
epochs:
  value: 2
gamma:
  value: 0.5409948202027501
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 128
starting_lr:
  value: 0.14038494421387393
