wandb_version: 1

batch_size:
  value: 10
epochs:
  value: 2
gamma:
  value: 0.056811075461203515
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.3961985580637775
