wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1660148974
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      4: 3.10.2
      5: 0.12.21
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 5
gamma:
  desc: null
  value: 0.18522144890039585
milestones:
  desc: null
  value:
  - 2
  - 6
optimizer:
  desc: null
  value: adam
second_layer_size:
  desc: null
  value: 128
starting_lr:
  desc: null
  value: 0.2121066907486712
sweep_epochs:
  desc: null
  value: 4
