wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 2
gamma:
  value: 0.025381457056420247
milestones:
  value:
  - 10
optimizer:
  value: adam
second_layer_size:
  value: 512
starting_lr:
  value: 0.375126166979717
