wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1660061613
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      4: 3.10.2
      5: 0.12.21
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 25
gamma:
  desc: null
  value: 0.18625144286176648
milestones:
  desc: null
  value:
  - 100000000
optimizer:
  desc: null
  value: sgd
second_layer_size:
  desc: null
  value: 128
starting_lr:
  desc: null
  value: 0.16632619320646289
sweep_epochs:
  desc: null
  value: 3
