wandb_version: 1

batch_size:
  value: 25
gamma:
  value: 0.18625144286176648
milestones:
  value:
  - 100000000
optimizer:
  value: sgd
second_layer_size:
  value: 128
starting_lr:
  value: 0.16632619320646289
sweep_epochs:
  value: 3
