wandb_version: 1

batch_size:
  value: 5
epochs:
  value: 2
gamma:
  value: 0.327114632506657
milestones:
  value:
  - 10
optimizer:
  value: sgd
second_layer_size:
  value: 128
starting_lr:
  value: 0.3954500153731904
